import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import {
  classifyByRules,
  decideSmartRoute,
  extractRoutingText,
  isSmartRoutingModel,
  parseAutoclawDirective,
} from '../src/smartRouting.mjs';
import { resolveModel } from '../src/routing.mjs';

// Generated by running horse-power's own route() calls (chatPayload.ts) and
// its directive builder (services/autoclawDirective.ts) over a prompt corpus:
// the enclave must pick the same model hp's path would. Regenerate with
// scripts/gen-autoclaw-parity.ts in the hp PR when the package or the tier
// config changes (see fixtures/autoclaw-parity.json "source").
const FIXTURES = JSON.parse(
  readFileSync(new URL('./fixtures/autoclaw-parity.json', import.meta.url), 'utf8'),
);
const directive = (key) => {
  const d = parseAutoclawDirective(FIXTURES.directives[key]);
  assert.ok(d, `directive ${key} must parse`);
  return d;
};
const promptOf = (c) => (c.prompt_repeat ? c.prompt_repeat.text.repeat(c.prompt_repeat.times) : c.prompt);
const payloadOf = (c) => ({
  model: c.directive,
  messages: [
    ...(c.system === null ? [] : [{ role: 'system', content: c.system }]),
    { role: 'user', content: promptOf(c) },
  ],
});

// ── parity with horse-power ──────────────────────────────────────────────────

test('every fixture decision matches hp (model, tier, confidence)', () => {
  assert.ok(FIXTURES.cases.length >= 200);
  const seenTiers = new Set();
  const seenTables = new Set();
  for (const c of FIXTURES.cases) {
    const d = decideSmartRoute(directive(c.directive), payloadOf(c));
    const label = `${c.directive} :: ${(c.prompt ?? 'REPEAT').slice(0, 60)}`;
    assert.equal(d.model, c.model, label);
    assert.equal(d.tier, c.tier, label);
    assert.ok(Math.abs(d.confidence - c.confidence) < 1e-6, `${label} confidence ${d.confidence} vs ${c.confidence}`);
    seenTiers.add(c.tier);
    seenTables.add(d.profile);
  }
  // The corpus exercises every tier and every table, so a broken branch cannot hide.
  assert.deepEqual([...seenTiers].sort(), ['COMPLEX', 'MEDIUM', 'REASONING', 'SIMPLE']);
  assert.deepEqual([...seenTables].sort(), ['agentic', 'auto', 'eco', 'premium']);
});

test('a custom autorouter list still falls into PPQ agentic table on agentic prompts, as hp does', () => {
  const custom = FIXTURES.cases.filter((c) => c.directive.startsWith('autorouter/a/'));
  const agentic = custom.filter((c) => c.model && !/^[abcd]\//.test(c.model));
  assert.ok(agentic.length > 0);
  for (const c of agentic) {
    const d = decideSmartRoute(directive(c.directive), payloadOf(c));
    assert.equal(d.profile, 'agentic');
    assert.equal(d.model, c.model);
  }
});

// ── parseAutoclawDirective ───────────────────────────────────────────────────

const good = () => JSON.parse(JSON.stringify(FIXTURES.directives['autoclaw/auto']));

test('parses hp directives for every family', () => {
  for (const key of Object.keys(FIXTURES.directives)) {
    const d = directive(key);
    assert.equal(d.profile, key === 'autoclaw/eco' ? 'eco' : key === 'autoclaw/premium' ? 'premium' : 'auto');
    assert.deepEqual(Object.keys(d.tiers), ['SIMPLE', 'MEDIUM', 'COMPLEX', 'REASONING']);
    assert.equal(d.custom, key.startsWith('autorouter/a/'));
    assert.equal(d.agenticTiers !== null, d.profile === 'auto');
  }
});

test('rejects the whole directive on any malformed part', () => {
  assert.equal(parseAutoclawDirective(null), null);
  assert.equal(parseAutoclawDirective('autoclaw/auto'), null);
  assert.equal(parseAutoclawDirective({}), null);
  const cases = [
    (d) => { d.profile = 'turbo'; },
    (d) => { delete d.tiers.COMPLEX; },
    (d) => { d.tiers.SIMPLE = 'not a slug!'; },
    (d) => { d.tiers.SIMPLE = { $ne: 'x' }; },
    (d) => { d.agentic_tiers = { SIMPLE: 'a/b' }; },
    (d) => { delete d.scoring.codeKeywords; },
    (d) => { d.scoring.codeKeywords = ['ok', 42]; },
    (d) => { d.scoring.codeKeywords = Array.from({ length: 501 }, (_, i) => `k${i}`); },
    (d) => { d.scoring.codeKeywords = ['x'.repeat(201)]; },
    (d) => { d.scoring.dimensionWeights.tokenCount = 'heavy'; },
    (d) => { delete d.scoring.dimensionWeights.agenticTask; },
    (d) => { d.scoring.tierBoundaries = { simpleMedium: 0 }; },
    (d) => { d.scoring.confidenceThreshold = Infinity; },
    (d) => { d.overrides.maxTokensForceComplex = 0; },
    (d) => { d.overrides.structuredOutputMinTier = 'HUGE'; },
    (d) => { d.overrides.ambiguousDefaultTier = null; },
    (d) => { d.overrides.agenticMode = 'yes'; },
    (d) => { d.promotions = 'none'; },
    (d) => { d.promotions = [{ startDate: '2026-01-01' }]; },
    (d) => { d.promotions = [{ startDate: '2026-01-01', endDate: '2026-02-01', tierOverrides: { SIMPLE: { primary: 'bad slug!' } } }]; },
    (d) => { d.promotions = [{ startDate: '2026-01-01', endDate: '2026-02-01', tierOverrides: { TURBO: { primary: 'a/b' } } }]; },
  ];
  for (const [i, mutate] of cases.entries()) {
    const d = good();
    mutate(d);
    assert.equal(parseAutoclawDirective(d), null, `case ${i}`);
  }
});

test('promotions and agentic_tiers are optional; custom flag is boolean', () => {
  const d = good();
  delete d.promotions;
  delete d.agentic_tiers;
  d.custom = 'yes';
  const p = parseAutoclawDirective(d);
  assert.ok(p);
  assert.deepEqual(p.promotions, []);
  assert.equal(p.agenticTiers, null);
  assert.equal(p.custom, false);
});

test('the parsed directive is a copy: mutating hp body afterwards changes nothing', () => {
  const raw = good();
  const p = parseAutoclawDirective(raw);
  raw.tiers.SIMPLE = 'evil/model';
  raw.scoring.codeKeywords.length = 0;
  assert.equal(p.tiers.SIMPLE, good().tiers.SIMPLE);
  assert.equal(p.scoring.codeKeywords.length, good().scoring.codeKeywords.length);
});

// ── decision mechanics not covered by the corpus shape ───────────────────────

test('extractRoutingText mirrors hp: last user message, first string system message', () => {
  const t = extractRoutingText({
    messages: [
      { role: 'system', content: [{ type: 'text', text: 'array system' }] },
      { role: 'user', content: 'first' },
      { role: 'assistant', content: 'reply' },
      { role: 'user', content: [{ type: 'text', text: 'second' }] },
    ],
  });
  assert.equal(t.prompt, JSON.stringify([{ type: 'text', text: 'second' }]));
  assert.equal(t.systemPrompt, undefined);
  assert.deepEqual(extractRoutingText({}), { prompt: '', systemPrompt: undefined });
  assert.deepEqual(extractRoutingText({ messages: [null, { role: 'user', content: null }] }), { prompt: '', systemPrompt: undefined });
  assert.equal(extractRoutingText({ messages: [{ role: 'system', content: 'sys' }] }).systemPrompt, 'sys');
});

test('agenticMode override forces or forbids the agentic table', () => {
  const d = directive('autoclaw/auto');
  const chat = { messages: [{ role: 'user', content: 'hi' }] };
  assert.equal(decideSmartRoute(d, chat).profile, 'auto');
  assert.equal(decideSmartRoute({ ...d, overrides: { ...d.overrides, agenticMode: true } }, chat).profile, 'agentic');
  const agenticPrompt = { messages: [{ role: 'user', content: 'please ' + d.scoring.agenticTaskKeywords.slice(0, 6).join(' and ') }] };
  assert.equal(decideSmartRoute(d, agenticPrompt).profile, 'agentic');
  assert.equal(decideSmartRoute({ ...d, overrides: { ...d.overrides, agenticMode: false } }, agenticPrompt).profile, 'auto');
  // eco/premium never use the agentic table
  assert.equal(decideSmartRoute(directive('autoclaw/eco'), agenticPrompt).profile, 'eco');
  assert.equal(decideSmartRoute(directive('autoclaw/premium'), agenticPrompt).profile, 'premium');
});

test('an active promotion swaps the tier model for the matching table only', () => {
  const d = directive('autoclaw/auto');
  const promo = {
    startDate: '2026-04-01',
    endDate: '2026-04-15',
    tierOverrides: { SIMPLE: { primary: 'promo/model' } },
    profiles: ['auto'],
  };
  const withPromo = { ...d, promotions: [promo] };
  const chat = { messages: [{ role: 'user', content: 'hi' }] };
  assert.equal(decideSmartRoute(withPromo, chat, new Date('2026-04-05')).model, 'promo/model');
  assert.equal(decideSmartRoute(withPromo, chat, new Date('2026-04-15')).model, d.tiers.SIMPLE);
  assert.equal(decideSmartRoute(withPromo, chat, new Date('2026-03-31')).model, d.tiers.SIMPLE);
  assert.equal(decideSmartRoute({ ...withPromo, promotions: [{ ...promo, profiles: ['eco'] }] }, chat, new Date('2026-04-05')).model, d.tiers.SIMPLE);
  assert.equal(d.tiers.SIMPLE, FIXTURES.directives['autoclaw/auto'].tiers.SIMPLE, 'input table untouched');
});

test('classifyByRules: two reasoning keywords force REASONING at >= 0.85 confidence', () => {
  const s = directive('autoclaw/auto').scoring;
  const r = classifyByRules(`${s.reasoningKeywords[0]} ${s.reasoningKeywords[1]}`, 10, s);
  assert.equal(r.tier, 'REASONING');
  assert.ok(r.confidence >= 0.85);
});

// ── model gate ───────────────────────────────────────────────────────────────

test('isSmartRoutingModel covers exactly the two families', () => {
  assert.equal(isSmartRoutingModel('autoclaw/auto'), true);
  assert.equal(isSmartRoutingModel('autorouter/a,b,c,d'), true);
  assert.equal(isSmartRoutingModel('openrouter/auto'), false);
  assert.equal(isSmartRoutingModel('autoclaw'), false);
  assert.equal(isSmartRoutingModel({ id: 'autoclaw/auto' }), false);
});

test('resolveModel no longer rejects smart-routing models, still rejects private/*', () => {
  const p = { model: 'autoclaw/auto' };
  resolveModel(p);
  assert.equal(p.model, 'autoclaw/auto');
  const q = { model: { id: 'autorouter/a,b,c,d' } };
  resolveModel(q);
  assert.equal(q.model, 'autorouter/a,b,c,d');
  assert.throws(() => resolveModel({ model: 'private/x' }), /Tinfoil/);
  assert.throws(() => resolveModel({ model: 5 }), /must be a string/);
});
