/**
 * Smart routing (`autoclaw/*`, `autorouter/*`) inside the enclave.
 *
 * A dependency-free port of the RULES strategy of @blockrun/clawrouter
 * 0.12.143 — `classifyByRules` and `RulesStrategy.route` — which is the only
 * part horse-power's chat path uses (services/chatPayload.ts). Everything
 * else in that package (wallets, x402 payments, pricing/savings, the LLM
 * fallback strategy) is deliberately not here: the trusted codebase stays
 * small and the decision needs nothing but the decrypted prompt.
 *
 * The enclave holds NO tier table or keyword list of its own. hp sends them
 * per request as the `autoclaw` directive of /authorize (horse-power
 * services/autoclawDirective.ts): profile, the four tier models, the agentic
 * table when the profile is `auto`, plus ClawRouter's `scoring`, `overrides`
 * and `promotions` verbatim. The enclave validates the shape and classifies.
 * This keeps the model catalog, the alias resolution and the tuning on hp,
 * exactly like the `auto_router` allow-list (routing.mjs).
 *
 * DRIFT HAZARD: the decision must equal what hp's own path would pick for
 * the same request. test/smartRouting.test.mjs replays fixtures generated by
 * running hp's `route()` calls; regenerate them when hp bumps the package or
 * changes utils/autoclaw-config.ts.
 */

import { MODEL_PATTERN } from './routing.mjs';

export const TIER_NAMES = ['SIMPLE', 'MEDIUM', 'COMPLEX', 'REASONING'];
const TIER_RANK = { SIMPLE: 0, MEDIUM: 1, COMPLEX: 2, REASONING: 3 };
const PROFILES = new Set(['auto', 'eco', 'premium']);

const KEYWORD_LISTS = [
  'codeKeywords',
  'reasoningKeywords',
  'simpleKeywords',
  'technicalKeywords',
  'creativeKeywords',
  'imperativeVerbs',
  'constraintIndicators',
  'outputFormatKeywords',
  'referenceKeywords',
  'negationKeywords',
  'domainSpecificKeywords',
  'agenticTaskKeywords',
];
const DIMENSION_NAMES = [
  'tokenCount',
  'codePresence',
  'reasoningMarkers',
  'technicalTerms',
  'creativeMarkers',
  'simpleIndicators',
  'multiStepPatterns',
  'questionComplexity',
  'imperativeVerbs',
  'constraintCount',
  'outputFormat',
  'referenceComplexity',
  'negationComplexity',
  'domainSpecificity',
  'agenticTask',
];
// Bounds on hp's config, so a drifted or runaway directive cannot turn the
// per-request classifier into a CPU sink (every keyword is an `includes`
// over the prompt). The real lists are 33..94 entries of a few words each.
const MAX_KEYWORDS = 500;
const MAX_KEYWORD_CHARS = 200;
const MAX_PROMOTIONS = 20;

/** The two model families hp routes with ClawRouter. */
export function isSmartRoutingModel(model) {
  return (
    typeof model === 'string' &&
    (model.startsWith('autoclaw/') || model.startsWith('autorouter/'))
  );
}

const isFinite_ = (n) => typeof n === 'number' && Number.isFinite(n);

function parseTiers(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const out = {};
  for (const t of TIER_NAMES) {
    const m = raw[t];
    if (typeof m !== 'string' || !MODEL_PATTERN.test(m)) return null;
    out[t] = m;
  }
  return out;
}

function parseKeywords(raw) {
  if (!Array.isArray(raw) || raw.length > MAX_KEYWORDS) return null;
  if (!raw.every((k) => typeof k === 'string' && k.length > 0 && k.length <= MAX_KEYWORD_CHARS)) return null;
  return [...raw];
}

function parseScoring(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const out = {};
  for (const name of KEYWORD_LISTS) {
    const list = parseKeywords(raw[name]);
    if (!list) return null;
    out[name] = list;
  }
  const th = raw.tokenCountThresholds;
  if (!th || typeof th !== 'object' || !isFinite_(th.simple) || !isFinite_(th.complex)) return null;
  out.tokenCountThresholds = { simple: th.simple, complex: th.complex };
  const w = raw.dimensionWeights;
  if (!w || typeof w !== 'object') return null;
  out.dimensionWeights = {};
  for (const name of DIMENSION_NAMES) {
    if (!isFinite_(w[name])) return null;
    out.dimensionWeights[name] = w[name];
  }
  const b = raw.tierBoundaries;
  if (!b || typeof b !== 'object') return null;
  for (const k of ['simpleMedium', 'mediumComplex', 'complexReasoning']) {
    if (!isFinite_(b[k])) return null;
  }
  out.tierBoundaries = {
    simpleMedium: b.simpleMedium,
    mediumComplex: b.mediumComplex,
    complexReasoning: b.complexReasoning,
  };
  if (!isFinite_(raw.confidenceSteepness) || !isFinite_(raw.confidenceThreshold)) return null;
  out.confidenceSteepness = raw.confidenceSteepness;
  out.confidenceThreshold = raw.confidenceThreshold;
  return out;
}

function parseOverrides(raw) {
  if (!raw || typeof raw !== 'object') return null;
  if (!isFinite_(raw.maxTokensForceComplex) || raw.maxTokensForceComplex <= 0) return null;
  if (!Object.hasOwn(TIER_RANK, raw.structuredOutputMinTier)) return null;
  if (!Object.hasOwn(TIER_RANK, raw.ambiguousDefaultTier)) return null;
  if (raw.agenticMode !== undefined && typeof raw.agenticMode !== 'boolean') return null;
  return {
    maxTokensForceComplex: raw.maxTokensForceComplex,
    structuredOutputMinTier: raw.structuredOutputMinTier,
    ambiguousDefaultTier: raw.ambiguousDefaultTier,
    agenticMode: raw.agenticMode,
  };
}

function parsePromotions(raw) {
  if (raw === undefined) return [];
  if (!Array.isArray(raw) || raw.length > MAX_PROMOTIONS) return null;
  const out = [];
  for (const p of raw) {
    if (!p || typeof p !== 'object') return null;
    if (typeof p.startDate !== 'string' || typeof p.endDate !== 'string') return null;
    if (!p.tierOverrides || typeof p.tierOverrides !== 'object') return null;
    const tierOverrides = {};
    for (const [tier, o] of Object.entries(p.tierOverrides)) {
      if (!Object.hasOwn(TIER_RANK, tier)) return null;
      if (!o || typeof o !== 'object') return null;
      if (o.primary !== undefined && (typeof o.primary !== 'string' || !MODEL_PATTERN.test(o.primary))) return null;
      tierOverrides[tier] = { primary: o.primary };
    }
    let profiles;
    if (p.profiles !== undefined) {
      if (!Array.isArray(p.profiles) || !p.profiles.every((x) => typeof x === 'string')) return null;
      profiles = [...p.profiles];
    }
    out.push({ startDate: p.startDate, endDate: p.endDate, tierOverrides, profiles });
  }
  return out;
}

/**
 * Validate hp's `autoclaw` directive, or null. Whole-directive rejection,
 * like parseAutoRouter: a half-parsed tier table would route to a model hp
 * never priced, and hp DRIFT (a renamed field) is the realistic failure.
 * Without a directive a smart-routing request gets the same 400 it always
 * got from this proxy (server.mjs), never a silent fallback model.
 */
export function parseAutoclawDirective(raw) {
  if (!raw || typeof raw !== 'object') return null;
  if (!PROFILES.has(raw.profile)) return null;
  const tiers = parseTiers(raw.tiers);
  if (!tiers) return null;
  let agenticTiers = null;
  if (raw.agentic_tiers !== undefined && raw.agentic_tiers !== null) {
    agenticTiers = parseTiers(raw.agentic_tiers);
    if (!agenticTiers) return null;
  }
  const scoring = parseScoring(raw.scoring);
  const overrides = parseOverrides(raw.overrides);
  const promotions = parsePromotions(raw.promotions);
  if (!scoring || !overrides || !promotions) return null;
  return {
    profile: raw.profile,
    tiers,
    agenticTiers,
    scoring,
    overrides,
    promotions,
    custom: raw.custom === true,
  };
}

// ── classifier: verbatim port of clawrouter's classifyByRules and helpers ──

function scoreKeywordMatch(text, keywords, name, thresholds, scores) {
  let matches = 0;
  for (const kw of keywords) if (text.includes(kw.toLowerCase())) matches++;
  if (matches >= thresholds.high) return { name, score: scores.high };
  if (matches >= thresholds.low) return { name, score: scores.low };
  return { name, score: scores.none };
}

function scoreAgenticTask(text, keywords) {
  let matchCount = 0;
  for (const kw of keywords) if (text.includes(kw.toLowerCase())) matchCount++;
  const agenticScore = matchCount >= 4 ? 1 : matchCount >= 3 ? 0.6 : matchCount >= 1 ? 0.2 : 0;
  return { dimensionScore: { name: 'agenticTask', score: agenticScore }, agenticScore };
}

function scoreMultiStep(text) {
  const patterns = [/first.*then/i, /step \d/i, /\d\.\s/];
  const hit = patterns.some((p) => p.test(text));
  return { name: 'multiStepPatterns', score: hit ? 0.5 : 0 };
}

function scoreQuestionComplexity(prompt) {
  const count = (prompt.match(/\?/g) || []).length;
  return { name: 'questionComplexity', score: count > 3 ? 0.5 : 0 };
}

function scoreTokenCount(estimatedTokens, thresholds) {
  if (estimatedTokens < thresholds.simple) return { name: 'tokenCount', score: -1 };
  if (estimatedTokens > thresholds.complex) return { name: 'tokenCount', score: 1 };
  return { name: 'tokenCount', score: 0 };
}

function calibrateConfidence(distance, steepness) {
  return 1 / (1 + Math.exp(-steepness * distance));
}

/** clawrouter classifyByRules(prompt, systemPrompt, estimatedTokens, config.scoring). */
export function classifyByRules(prompt, estimatedTokens, config) {
  const userText = prompt.toLowerCase();
  const kw = (list, name, thresholds, scores) =>
    scoreKeywordMatch(userText, config[list], name, thresholds, scores);
  const dimensions = [
    scoreTokenCount(estimatedTokens, config.tokenCountThresholds),
    kw('codeKeywords', 'codePresence', { low: 1, high: 2 }, { none: 0, low: 0.5, high: 1 }),
    kw('reasoningKeywords', 'reasoningMarkers', { low: 1, high: 2 }, { none: 0, low: 0.7, high: 1 }),
    kw('technicalKeywords', 'technicalTerms', { low: 2, high: 4 }, { none: 0, low: 0.5, high: 1 }),
    kw('creativeKeywords', 'creativeMarkers', { low: 1, high: 2 }, { none: 0, low: 0.5, high: 0.7 }),
    kw('simpleKeywords', 'simpleIndicators', { low: 1, high: 2 }, { none: 0, low: -1, high: -1 }),
    scoreMultiStep(userText),
    scoreQuestionComplexity(prompt),
    kw('imperativeVerbs', 'imperativeVerbs', { low: 1, high: 2 }, { none: 0, low: 0.3, high: 0.5 }),
    kw('constraintIndicators', 'constraintCount', { low: 1, high: 3 }, { none: 0, low: 0.3, high: 0.7 }),
    kw('outputFormatKeywords', 'outputFormat', { low: 1, high: 2 }, { none: 0, low: 0.4, high: 0.7 }),
    kw('referenceKeywords', 'referenceComplexity', { low: 1, high: 2 }, { none: 0, low: 0.3, high: 0.5 }),
    kw('negationKeywords', 'negationComplexity', { low: 2, high: 3 }, { none: 0, low: 0.3, high: 0.5 }),
    kw('domainSpecificKeywords', 'domainSpecificity', { low: 1, high: 2 }, { none: 0, low: 0.5, high: 0.8 }),
  ];
  const agentic = scoreAgenticTask(userText, config.agenticTaskKeywords);
  dimensions.push(agentic.dimensionScore);
  const agenticScore = agentic.agenticScore;

  const weights = config.dimensionWeights;
  let weightedScore = 0;
  for (const d of dimensions) weightedScore += d.score * (weights[d.name] ?? 0);

  let reasoningMatches = 0;
  for (const k of config.reasoningKeywords) if (userText.includes(k.toLowerCase())) reasoningMatches++;
  if (reasoningMatches >= 2) {
    const c = calibrateConfidence(Math.max(weightedScore, 0.3), config.confidenceSteepness);
    return { score: weightedScore, tier: 'REASONING', confidence: Math.max(c, 0.85), agenticScore };
  }

  const { simpleMedium, mediumComplex, complexReasoning } = config.tierBoundaries;
  let tier;
  let distance;
  if (weightedScore < simpleMedium) {
    tier = 'SIMPLE';
    distance = simpleMedium - weightedScore;
  } else if (weightedScore < mediumComplex) {
    tier = 'MEDIUM';
    distance = Math.min(weightedScore - simpleMedium, mediumComplex - weightedScore);
  } else if (weightedScore < complexReasoning) {
    tier = 'COMPLEX';
    distance = Math.min(weightedScore - mediumComplex, complexReasoning - weightedScore);
  } else {
    tier = 'REASONING';
    distance = weightedScore - complexReasoning;
  }
  const confidence = calibrateConfidence(distance, config.confidenceSteepness);
  if (confidence < config.confidenceThreshold) {
    return { score: weightedScore, tier: null, confidence, agenticScore };
  }
  return { score: weightedScore, tier, confidence, agenticScore };
}

/** clawrouter applyPromotions, on a flat {tier: model} table. */
function applyPromotions(tiers, promotions, profile, now) {
  let result = tiers;
  for (const promo of promotions) {
    const start = new Date(promo.startDate);
    const end = new Date(promo.endDate);
    if (now < start || now >= end) continue;
    if (promo.profiles && !promo.profiles.includes(profile)) continue;
    if (result === tiers) result = { ...tiers };
    for (const [tier, o] of Object.entries(promo.tierOverrides)) {
      if (!result[tier]) continue;
      if (o.primary) result[tier] = o.primary;
    }
  }
  return result;
}

/**
 * The prompt hp's chat path hands ClawRouter: the LAST user message (a
 * non-string content array is JSON-stringified, as hp does) and the FIRST
 * system message when its content is a string (otherwise no system prompt).
 * Mirrors chatPayload.ts; any other message is not consulted.
 */
export function extractRoutingText(payload) {
  const messages = Array.isArray(payload?.messages) ? payload.messages : [];
  let lastUser = '';
  for (const m of messages) if (m && m.role === 'user') lastUser = m.content ?? '';
  const systemContent = messages.find((m) => m && m.role === 'system')?.content;
  return {
    prompt: typeof lastUser === 'string' ? lastUser : JSON.stringify(lastUser),
    systemPrompt: typeof systemContent === 'string' ? systemContent : undefined,
  };
}

/**
 * clawrouter RulesStrategy.route, minus pricing. hp never passes `hasTools`
 * (its options carry only config/pricing/profile), so a request with tools
 * is agentic here only through the agentic keyword score — same as on hp.
 *
 * Returns { model, tier, confidence, profile } where profile is the table
 * used: 'auto' | 'agentic' | 'eco' | 'premium'.
 */
export function decideSmartRoute(directive, payload, now = new Date()) {
  const { prompt, systemPrompt } = extractRoutingText(payload);
  const { scoring, overrides } = directive;
  const estimatedTokens = Math.ceil(`${systemPrompt ?? ''} ${prompt}`.length / 4);
  const rule = classifyByRules(prompt, estimatedTokens, scoring);

  let tiers;
  let profile;
  if (directive.profile === 'eco' || directive.profile === 'premium') {
    tiers = directive.tiers;
    profile = directive.profile;
  } else {
    const isAutoAgentic = (rule.agenticScore ?? 0) >= 0.5;
    let useAgentic;
    if (overrides.agenticMode === false) useAgentic = false;
    else if (overrides.agenticMode === true) useAgentic = directive.agenticTiers != null;
    else useAgentic = isAutoAgentic && directive.agenticTiers != null;
    tiers = useAgentic ? directive.agenticTiers : directive.tiers;
    profile = useAgentic ? 'agentic' : 'auto';
  }
  tiers = applyPromotions(tiers, directive.promotions, profile, now);

  if (estimatedTokens > overrides.maxTokensForceComplex) {
    return { model: tiers.COMPLEX, tier: 'COMPLEX', confidence: 0.95, profile };
  }

  let tier;
  let confidence;
  if (rule.tier !== null) {
    tier = rule.tier;
    confidence = rule.confidence;
  } else {
    tier = overrides.ambiguousDefaultTier;
    confidence = 0.5;
  }
  const hasStructuredOutput = systemPrompt ? /json|structured|schema/i.test(systemPrompt) : false;
  if (hasStructuredOutput && TIER_RANK[tier] < TIER_RANK[overrides.structuredOutputMinTier]) {
    tier = overrides.structuredOutputMinTier;
  }
  return { model: tiers[tier], tier, confidence, profile };
}
